// silver-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'silver-angular';
}

<silver-card title="Silver Card!">
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit.
    </p>
</silver-card>
<router-outlet></router-outlet>

// silver-vue/src/App.vue
<template>
  <div id="app">
    <silver-card title="Hello">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </p>
    </silver-card>
  </div>
</template>

<script>
export default {
  name: 'app',
  components: {
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
